version: '3.8'

services:
  # Combined Frontend + Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: json-generator-app
    ports:
      - "80:80"
    environment:
      - TZ=UTC
      - NODE_ENV=production
      - GIN_MODE=release
    volumes:
      - uploads:/uploads
      - logs:/logs
    networks:
      - json-generator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Development version (optional)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: json-generator-app-dev
    ports:
      - "8080:80"
    environment:
      - TZ=UTC
      - NODE_ENV=development
      - GIN_MODE=debug
    volumes:
      - uploads:/uploads
      - logs:/logs
      - .:/app/src:ro  # Mount source for development
    networks:
      - json-generator-network
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  json-generator-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local
